export {
	MAX_DEPTH,
	MAX_TIME_MS,
	type StockfishDifficulty,
	type StockfishMove,
	type MoveAnalysis,
	type PositionAnalysis,
	type GameAnalysis,
	type ErrorCallback,
	StockfishPool,
	getStockfishPool,
	resetStockfishPool,
	clampDepth,
	createStockfish,
	parseBestMove,
	parseInfoLine,
	getDifficultySettings,
	calculateAccuracy,
	classifyMove,
	createMoveAnalysis,
} from './stockfish-pool.svelte';
