sonar.projectKey=Jonathangadeaharder_Chess
sonar.organization=jonathangadeaharder

sonar.exclusions=tests/**,test-results/**,**/*.test.ts,**/*.spec.ts,static/stockfish/worker.js
sonar.cpd.exclusions=tests/**,**/*.test.ts,**/*.spec.ts,**/icons/*.svelte,static/stockfish/worker.js
